var PIZZA_BASE = [
    'margherita',
    'polo',
    'pepperoni',
    'siciliana',
    'florentina',
    'pescatora',
    'frutti de mare',
    'quattro formaggi',
    'vegitariano',
    'tomato & cipolta',
    'bianca',
    'greco',
    'polpettine',
    'tropicana',
    'quattro stagioni',
    'mexicana',
    'goat cheese'
];

var TOPPINGS = [
    'cheese',
    'mushrooms',
    'pepperoni',
    'mozzarella',
    'anchovies',
    'olives',
    'capers',
    'spinach',
    'egg',
    'seafood',
    'parmigiano',
    'aubergines',
    'courgette',
    'peppers',
    'sweetcorn',
    'tuna',
    'onions',
    'asparagus',
    'tomatoes',
    'feta',
    'meatballs',
    'pineapple',
    'ham',
    'artichoke',
    'jalapenos'
];

